"""Add external user fields

Revision ID: 7939e09c25f2
Revises: b1c2d3e4f5g6
Create Date: 2026-03-03 16:27:05.781832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7939e09c25f2'
down_revision: Union[str, None] = 'b1c2d3e4f5g6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_team_name', table_name='documents')
    op.drop_index('ix_schedules_team_name', table_name='schedules')
    op.add_column('users', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('avatar', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'address')
    op.drop_column('users', 'phone')
    op.create_index('ix_schedules_team_name', 'schedules', ['team_name'], unique=False)
    op.create_index('ix_documents_team_name', 'documents', ['team_name'], unique=False)
    # ### end Alembic commands ###
