"""add messages table

Revision ID: ccceaaad855b
Revises: e5a3168eb5d1
Create Date: 2026-03-05 12:26:22.272376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccceaaad855b'
down_revision: Union[str, None] = 'e5a3168eb5d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('action_items', 'meeting_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_documents_team_name', table_name='documents')
    op.drop_index('ix_schedules_team_name', table_name='schedules')
    op.alter_column('users', 'slack_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'slack_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index('ix_schedules_team_name', 'schedules', ['team_name'], unique=False)
    op.create_index('ix_documents_team_name', 'documents', ['team_name'], unique=False)
    op.alter_column('action_items', 'meeting_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('messages')
    # ### end Alembic commands ###
