"""Add session_id, assignee_id, TEXT to JSONB

Revision ID: ff4b6e2ab2e5
Revises: 77cfec3c68a0
Create Date: 2026-02-11 11:33:34.802511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff4b6e2ab2e5'
down_revision: Union[str, None] = '77cfec3c68a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action_items', sa.Column('assignee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'action_items', 'users', ['assignee_id'], ['id'])
    op.add_column('chat_logs', sa.Column('session_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_chat_logs_session_id'), 'chat_logs', ['session_id'], unique=False)
    op.execute('ALTER TABLE judgments ALTER COLUMN regulations_cited TYPE JSONB USING regulations_cited::jsonb')
    op.execute('ALTER TABLE meetings ALTER COLUMN decisions TYPE JSONB USING decisions::jsonb')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meetings', 'decisions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('judgments', 'regulations_cited',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_chat_logs_session_id'), table_name='chat_logs')
    op.drop_column('chat_logs', 'session_id')
    op.drop_constraint(None, 'action_items', type_='foreignkey')
    op.drop_column('action_items', 'assignee_id')
    # ### end Alembic commands ###
